server:
  port: 8880
spring:
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    encoding: "UTF-8"
    servlet:
      content-type: text/html
    mode: HTML5
  datasource:
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://144.34.139.23:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
#    password: 123654
    password: root
mybatis:
  type-aliases-package: cn.hero.model
  mapper-locations: classpath:/cn/hero/provider/db/mapper/*.xml