server:
  port: 8880
spring:
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: '.html'
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123654
mybatis:
  type-aliases-package: cn.hero.model
  mapper-locations: classpath:/cn/hero/provider/db/mapper/*.xml